@startuml
set separator none

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  componentStyle uml1
}

hide stereotype

skinparam component<<ItineraryApplication.ItineraryApplication.Routes>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<ItineraryApplication.ItineraryApplication>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

component "==Routes\n<size:10>[Component: Module]</size>" <<ItineraryApplication.ItineraryApplication.Routes>> as ItineraryApplication.ItineraryApplication.Routes
@enduml